### ISSUE TITLE
Hero space for one movie

### ISSUE THREAD

**Issue by chartreusemongoose** [chartreusemongoose/movie-compass#23]
**User Story**
When a user visits the website, a movie's poster and description takes up the hero space-- this takes up the majority of the screen on landing, before they have scrolled. 

**Acceptance Criteria**
- Before we are able to display info for several movies, display the poster/info for just one movie (pulled from an API). 
- The movie's poster takes up the full screen
- The movie's title, info, and short plot is displayed on a small overlay on the bottom left

**Comment by johnpaulfernandez** [comment]
Pushed PR https://github.com/chartreusemongoose/movie-compass/pull/28
