### ISSUE TITLE
Determine which APIs to use

### ISSUE THREAD

**Issue by chartreusemongoose** [chartreusemongoose/movie-compass#6]

**Comment by chartreusemongoose** [comment]
- Fandango API docs are awful, but they might have what we need
- MovieGlu API looks like exactly what we need, but it'll cost money
- Google showtimes API got scrapped (?), but we might have some option there
- Still investigating other options

**Comment by chartreusemongoose** [comment]
Currently reviewing Gracenote Developer API

**Comment by chartreusemongoose** [comment]
Using Gracenote Developer API at the free level during development. For later production we can review the paid options.

**Comment by johnpaulfernandez** [comment]
Gracenote can be used to obtain the following information:
- movies playing in local theaters based on zip code/geolocation
- theater showtimes
- geolocation of local theaters

 However, Gracenote does not provide access to movie poster images for free. [FAQ](http://developer.tmsapi.com/page/Frequently_Asked_Questions#Data%20Related%20Questions)

 
To display images, The Movie DB API can be used alongside Gracenote. The API can also be used to get reviews and post user reviews for a movie.

**Comment by chartreusemongoose** [comment]
No remaining work on this issue. Closing.
